version: '3.8'
services:
  metabase:
    build:
      context: ./metabase  
      dockerfile: Dockerfile 
    container_name: metaduck
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./duckdb/
        target: /duckdb/ 
      - type: bind
        source: ./metabase/
        target: /metabase/
    environment:
      - MB_DB_FILE=/metabase/metadata/metabase.db
    mem_limit: 2GB