services:
  metabase:
    build:
      context: ./metabase  
      dockerfile: Dockerfile 
    container_name: metaduck
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./duckdb/
        target: /duckdb/ 
      - type: bind
        source: ./metabase/
        target: /metabase/
    environment:
      - MB_DB_FILE=/metabase/metadata/metabase.db
    mem_limit: 2GB

  minio:
    build:
      context: ./minio  
      dockerfile: Dockerfile 
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_CONFIG_ENV_FILE=/etc/config.env
    command: server /data --console-address :9001