CREATE TABLE {destination_table_name} AS
SELECT
    CAST(partida_id AS INT) AS id_partida,
    campeonato['nome'] AS championship_name,
    campeonato['edicao']['temporada'] AS season,
    time_mandante['nome_popular'] AS home_team,
    time_visitante['nome_popular'] AS away_team,
    placar_mandante AS home_score,
    placar_visitante AS away_score,
    status,
    data_realizacao_iso AS dt_game_day,
    REPLACE(estatisticas.mandante.posse_de_bola, '"', '') AS home_ball_possession,
    estatisticas.mandante.escanteios AS home_corners,
    estatisticas.mandante.impedimentos AS home_offside,
    estatisticas.mandante.passes.total AS home_passes,
    estatisticas.mandante.passes.completos AS home_passes_completed,
    estatisticas.mandante.passes.errados AS home_passes_failed,
    estatisticas.mandante.finalizacao.total AS home_shoots,
    estatisticas.mandante.finalizacao.no_gol AS home_shoots_on_goal,
    estatisticas.mandante.finalizacao.pra_fora AS home_shoots_off_goal,
    estatisticas.mandante.finalizacao.na_trave AS home_shoots_on_crossbar,
    estatisticas.mandante.finalizacao.bloqueado AS home_shoots_blocked,
    estatisticas.mandante.defensivo.defesas AS home_defenses,
    estatisticas.mandante.desarmes AS home_disarms,
    escalacoes.mandante.esquema_tatico AS home_tactical_schema,
    REPLACE(estatisticas.visitante.posse_de_bola, '"', '') AS away_ball_possession,
    estatisticas.visitante.escanteios AS away_corners,
    estatisticas.visitante.impedimentos AS away_offside,
    estatisticas.visitante.passes.total AS away_passes,
    estatisticas.visitante.passes.completos AS away_passes_completed,
    estatisticas.visitante.passes.errados AS away_passes_failed,
    estatisticas.visitante.finalizacao.total AS away_shoots,
    estatisticas.visitante.finalizacao.no_gol AS away_shoots_on_goal,
    estatisticas.visitante.finalizacao.pra_fora AS away_shoots_off_goal,
    estatisticas.visitante.finalizacao.na_trave AS away_shoots_on_crossbar,
    estatisticas.visitante.finalizacao.bloqueado AS away_shoots_blocked,
    estatisticas.visitante.defensivo.defesas AS away_defenses,
    estatisticas.visitante.desarmes AS away_disarms,
    escalacoes.visitante.esquema_tatico AS away_tactical_schema
FROM read_json_auto('{s3_path}', union_by_name=True);